export const PROJECT_DETAILS_REQUEST = 'PROJECT_DETAILS_REQUEST';
export const PROJECT_DETAILS_SUCCESS = 'PROJECT_DETAILS_SUCCESS';
export const PROJECT_DETAILS_FAIL = 'PROJECT_DETAILS_FAIL';



export const PROJECT_CATEGORY_LIST_REQUEST = 'PROJECT_CATEGORY_LIST_REQUEST';
export const PROJECT_CATEGORY_LIST_SUCCESS = 'PROJECT_CATEGORY_LIST_SUCCESS';
export const PROJECT_CATEGORY_LIST_FAIL = 'PROJECT_CATEGORY_LIST_FAIL';

export const LOGO_PROJECT_LIST_REQUEST = 'LOGO_PROJECT_LIST_REQUEST';
export const LOGO_PROJECT_LIST_SUCCESS = 'LOGO_PROJECT_LIST_SUCCESS';
export const LOGO_PROJECT_LIST_FAIL = 'LOGO_PROJECT_LIST_FAIL';


export const BROCHURE_PROJECT_LIST_REQUEST = 'BROCHURE_PROJECT_LIST_REQUEST';
export const BROCHURE_PROJECT_LIST_SUCCESS = 'BROCHURE_PROJECT_LIST_SUCCESS';
export const BROCHURE_PROJECT_LIST_FAIL = 'BROCHURE_PROJECT_LIST_FAIL';


export const EDITORIAL_PROJECT_LIST_REQUEST = 'EDITORIAL_PROJECT_LIST_REQUEST';
export const EDITORIAL_PROJECT_LIST_SUCCESS = 'EDITORIAL_PROJECT_LIST_SUCCESS';
export const EDITORIAL_PROJECT_LIST_FAIL = 'EDITORIAL_PROJECT_LIST_FAIL';


export const UI_PROJECT_LIST_REQUEST = 'UI_PROJECT_LIST_REQUEST';
export const UI_PROJECT_LIST_SUCCESS = 'UI_PROJECT_LIST_SUCCESS';
export const UI_PROJECT_LIST_FAIL = 'UI_PROJECT_LIST_FAIL';


